unit CliMain;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, JSocket;
type
  TFrmAccServer=class(TForm)
    SServer: TServerSocket;
    DecodeTimer: TTimer;
    TimeOutTimer: TTimer;
    CheckTimeoutTimer: TTimer;
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAccServer: TFrmAccServer;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

end.
