unit FAccount;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls;
type
  TFrmAccountForm=class(TForm)
    EdID: TEdit;
    EdChrName: TEdit;
    Label1: TLabel;
    Label2: TLabel;
    Label3: TLabel;
    CbFeeMode: TComboBox;
    Label4: TLabel;
    EdYear: TEdit;
    EdMon: TEdit;
    EdDay: TEdit;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    EdCount: TEdit;
    Label8: TLabel;
    Label9: TLabel;
    EdMemo: TEdit;
    Label10: TLabel;
    Button1: TButton;
    Button2: TButton;
    EdOwner: TEdit;
    Label11: TLabel;
    EdDupCount: TEdit;
    Label12: TLabel;
  private
    { Private declarations }
  public
    { Public declarations }
  end ;

var
  FrmAccountForm: TFrmAccountForm;

{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}

end.
